// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClHRkMWy_BFEpyfSDotfOVhc1JjkxjmHo',
    appId: '1:645560434000:android:b9c9a10355f1cd7df1c055',
    messagingSenderId: '645560434000',
    projectId: 'neighboursadda-11bb0',
    storageBucket: 'neighboursadda-11bb0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8_gLHZAweGIqBRbkmUFFzzpp0FCTDA_M',
    appId: '1:645560434000:ios:49b10f9f6c0cce5bf1c055',
    messagingSenderId: '645560434000',
    projectId: 'neighboursadda-11bb0',
    storageBucket: 'neighboursadda-11bb0.appspot.com',
    androidClientId: '645560434000-0rs1ap92uqqvdpu22iktjrv55adp19c1.apps.googleusercontent.com',
    iosClientId: '645560434000-9hln75mggcv8a0fm68c5k7mnhch9ca2d.apps.googleusercontent.com',
    iosBundleId: 'com.snaplocal.app',
  );

}